Posts:
  controller: posts
  nav_type: default
  path: /posts

Polls:
  controller: polls
  nav_type: default
  path: /polls

Chat:
  controller: chat_messages
  nav_type: default
  path: /chat_messages

Email:
  controller: emails
  nav_type: dropdown
  item:
    Create New Email:
      path: /users/#{current_user.id}/emails/new
    
    Separator:
    
    My Emails:
      path: /users/#{current_user.id}/emails